DROP TABLE IF EXISTS `shop_profile`;#用户资料
CREATE TABLE IF NOT EXISTS `shop_profile`(
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
 `true_name` VARCHAR (32) NOT NULL DEFAULT '' COMMENT '真实姓名',
 `age` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '年龄',
 `sex` ENUM('0','1','2') NOT  NULL DEFAULT '0' COMMENT '性别',
 `birthday` DATE NOT NULL DEFAULT '2016-01-01' COMMENT '生日',
 `nick_name` VARCHAR (32) NOT NULL DEFAULT '' COMMENT '昵称',
 `company` VARCHAR (100) NOT NULL DEFAULT '' COMMENT '公司',
 `user_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户ID',
 `create_time` INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '创建时间',
 PRIMARY KEY (`id`),
 UNIQUE shop_profile_user_id(`user_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;